// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taint-tracking.proto

package tainttracking

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilterRequest struct {
	GetVel               bool     `protobuf:"varint,1,opt,name=getVel,proto3" json:"getVel,omitempty"`
	IncVel               bool     `protobuf:"varint,2,opt,name=incVel,proto3" json:"incVel,omitempty"`
	DecVel               bool     `protobuf:"varint,3,opt,name=decVel,proto3" json:"decVel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{0}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetGetVel() bool {
	if m != nil {
		return m.GetVel
	}
	return false
}

func (m *FilterRequest) GetIncVel() bool {
	if m != nil {
		return m.IncVel
	}
	return false
}

func (m *FilterRequest) GetDecVel() bool {
	if m != nil {
		return m.DecVel
	}
	return false
}

type FilterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GetVel               bool     `protobuf:"varint,2,opt,name=getVel,proto3" json:"getVel,omitempty"`
	IncVel               bool     `protobuf:"varint,3,opt,name=incVel,proto3" json:"incVel,omitempty"`
	DecVel               bool     `protobuf:"varint,4,opt,name=decVel,proto3" json:"decVel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterReply) Reset()         { *m = FilterReply{} }
func (m *FilterReply) String() string { return proto.CompactTextString(m) }
func (*FilterReply) ProtoMessage()    {}
func (*FilterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{1}
}

func (m *FilterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterReply.Unmarshal(m, b)
}
func (m *FilterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterReply.Marshal(b, m, deterministic)
}
func (m *FilterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterReply.Merge(m, src)
}
func (m *FilterReply) XXX_Size() int {
	return xxx_messageInfo_FilterReply.Size(m)
}
func (m *FilterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterReply.DiscardUnknown(m)
}

var xxx_messageInfo_FilterReply proto.InternalMessageInfo

func (m *FilterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *FilterReply) GetGetVel() bool {
	if m != nil {
		return m.GetVel
	}
	return false
}

func (m *FilterReply) GetIncVel() bool {
	if m != nil {
		return m.IncVel
	}
	return false
}

func (m *FilterReply) GetDecVel() bool {
	if m != nil {
		return m.DecVel
	}
	return false
}

type LogRequest struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Code                 bool     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{2}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *LogRequest) GetCode() bool {
	if m != nil {
		return m.Code
	}
	return false
}

type LogReply struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Code                 bool     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReply) Reset()         { *m = LogReply{} }
func (m *LogReply) String() string { return proto.CompactTextString(m) }
func (*LogReply) ProtoMessage()    {}
func (*LogReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{3}
}

func (m *LogReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReply.Unmarshal(m, b)
}
func (m *LogReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReply.Marshal(b, m, deterministic)
}
func (m *LogReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReply.Merge(m, src)
}
func (m *LogReply) XXX_Size() int {
	return xxx_messageInfo_LogReply.Size(m)
}
func (m *LogReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogReply proto.InternalMessageInfo

func (m *LogReply) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *LogReply) GetCode() bool {
	if m != nil {
		return m.Code
	}
	return false
}

type VelocityRequest struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Log                  bool     `protobuf:"varint,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VelocityRequest) Reset()         { *m = VelocityRequest{} }
func (m *VelocityRequest) String() string { return proto.CompactTextString(m) }
func (*VelocityRequest) ProtoMessage()    {}
func (*VelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{4}
}

func (m *VelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VelocityRequest.Unmarshal(m, b)
}
func (m *VelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VelocityRequest.Marshal(b, m, deterministic)
}
func (m *VelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VelocityRequest.Merge(m, src)
}
func (m *VelocityRequest) XXX_Size() int {
	return xxx_messageInfo_VelocityRequest.Size(m)
}
func (m *VelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VelocityRequest proto.InternalMessageInfo

func (m *VelocityRequest) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

func (m *VelocityRequest) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

type VelocityReply struct {
	Velocity             int32    `protobuf:"varint,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Log                  bool     `protobuf:"varint,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VelocityReply) Reset()         { *m = VelocityReply{} }
func (m *VelocityReply) String() string { return proto.CompactTextString(m) }
func (*VelocityReply) ProtoMessage()    {}
func (*VelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{5}
}

func (m *VelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VelocityReply.Unmarshal(m, b)
}
func (m *VelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VelocityReply.Marshal(b, m, deterministic)
}
func (m *VelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VelocityReply.Merge(m, src)
}
func (m *VelocityReply) XXX_Size() int {
	return xxx_messageInfo_VelocityReply.Size(m)
}
func (m *VelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_VelocityReply proto.InternalMessageInfo

func (m *VelocityReply) GetVelocity() int32 {
	if m != nil {
		return m.Velocity
	}
	return 0
}

func (m *VelocityReply) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

type IncVelocityRequest struct {
	Inc                  int32    `protobuf:"varint,1,opt,name=inc,proto3" json:"inc,omitempty"`
	Log                  bool     `protobuf:"varint,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncVelocityRequest) Reset()         { *m = IncVelocityRequest{} }
func (m *IncVelocityRequest) String() string { return proto.CompactTextString(m) }
func (*IncVelocityRequest) ProtoMessage()    {}
func (*IncVelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{6}
}

func (m *IncVelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncVelocityRequest.Unmarshal(m, b)
}
func (m *IncVelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncVelocityRequest.Marshal(b, m, deterministic)
}
func (m *IncVelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncVelocityRequest.Merge(m, src)
}
func (m *IncVelocityRequest) XXX_Size() int {
	return xxx_messageInfo_IncVelocityRequest.Size(m)
}
func (m *IncVelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncVelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncVelocityRequest proto.InternalMessageInfo

func (m *IncVelocityRequest) GetInc() int32 {
	if m != nil {
		return m.Inc
	}
	return 0
}

func (m *IncVelocityRequest) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

type IncVelocityReply struct {
	ReturnCode           bool     `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	NewVelocity          int32    `protobuf:"varint,2,opt,name=new_velocity,json=newVelocity,proto3" json:"new_velocity,omitempty"`
	Log                  bool     `protobuf:"varint,3,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncVelocityReply) Reset()         { *m = IncVelocityReply{} }
func (m *IncVelocityReply) String() string { return proto.CompactTextString(m) }
func (*IncVelocityReply) ProtoMessage()    {}
func (*IncVelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{7}
}

func (m *IncVelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncVelocityReply.Unmarshal(m, b)
}
func (m *IncVelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncVelocityReply.Marshal(b, m, deterministic)
}
func (m *IncVelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncVelocityReply.Merge(m, src)
}
func (m *IncVelocityReply) XXX_Size() int {
	return xxx_messageInfo_IncVelocityReply.Size(m)
}
func (m *IncVelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IncVelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_IncVelocityReply proto.InternalMessageInfo

func (m *IncVelocityReply) GetReturnCode() bool {
	if m != nil {
		return m.ReturnCode
	}
	return false
}

func (m *IncVelocityReply) GetNewVelocity() int32 {
	if m != nil {
		return m.NewVelocity
	}
	return 0
}

func (m *IncVelocityReply) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

type DecVelocityRequest struct {
	Dec                  int32    `protobuf:"varint,1,opt,name=dec,proto3" json:"dec,omitempty"`
	Log                  bool     `protobuf:"varint,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecVelocityRequest) Reset()         { *m = DecVelocityRequest{} }
func (m *DecVelocityRequest) String() string { return proto.CompactTextString(m) }
func (*DecVelocityRequest) ProtoMessage()    {}
func (*DecVelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{8}
}

func (m *DecVelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecVelocityRequest.Unmarshal(m, b)
}
func (m *DecVelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecVelocityRequest.Marshal(b, m, deterministic)
}
func (m *DecVelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecVelocityRequest.Merge(m, src)
}
func (m *DecVelocityRequest) XXX_Size() int {
	return xxx_messageInfo_DecVelocityRequest.Size(m)
}
func (m *DecVelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecVelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecVelocityRequest proto.InternalMessageInfo

func (m *DecVelocityRequest) GetDec() int32 {
	if m != nil {
		return m.Dec
	}
	return 0
}

func (m *DecVelocityRequest) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

type DecVelocityReply struct {
	ReturnCode           bool     `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	NewVelocity          int32    `protobuf:"varint,2,opt,name=new_velocity,json=newVelocity,proto3" json:"new_velocity,omitempty"`
	Log                  bool     `protobuf:"varint,3,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecVelocityReply) Reset()         { *m = DecVelocityReply{} }
func (m *DecVelocityReply) String() string { return proto.CompactTextString(m) }
func (*DecVelocityReply) ProtoMessage()    {}
func (*DecVelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_118de55f31689bed, []int{9}
}

func (m *DecVelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecVelocityReply.Unmarshal(m, b)
}
func (m *DecVelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecVelocityReply.Marshal(b, m, deterministic)
}
func (m *DecVelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecVelocityReply.Merge(m, src)
}
func (m *DecVelocityReply) XXX_Size() int {
	return xxx_messageInfo_DecVelocityReply.Size(m)
}
func (m *DecVelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DecVelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_DecVelocityReply proto.InternalMessageInfo

func (m *DecVelocityReply) GetReturnCode() bool {
	if m != nil {
		return m.ReturnCode
	}
	return false
}

func (m *DecVelocityReply) GetNewVelocity() int32 {
	if m != nil {
		return m.NewVelocity
	}
	return 0
}

func (m *DecVelocityReply) GetLog() bool {
	if m != nil {
		return m.Log
	}
	return false
}

func init() {
	proto.RegisterType((*FilterRequest)(nil), "tainttracking.FilterRequest")
	proto.RegisterType((*FilterReply)(nil), "tainttracking.FilterReply")
	proto.RegisterType((*LogRequest)(nil), "tainttracking.LogRequest")
	proto.RegisterType((*LogReply)(nil), "tainttracking.LogReply")
	proto.RegisterType((*VelocityRequest)(nil), "tainttracking.VelocityRequest")
	proto.RegisterType((*VelocityReply)(nil), "tainttracking.VelocityReply")
	proto.RegisterType((*IncVelocityRequest)(nil), "tainttracking.IncVelocityRequest")
	proto.RegisterType((*IncVelocityReply)(nil), "tainttracking.IncVelocityReply")
	proto.RegisterType((*DecVelocityRequest)(nil), "tainttracking.DecVelocityRequest")
	proto.RegisterType((*DecVelocityReply)(nil), "tainttracking.DecVelocityReply")
}

func init() { proto.RegisterFile("taint-tracking.proto", fileDescriptor_118de55f31689bed) }

var fileDescriptor_118de55f31689bed = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4b, 0x8f, 0xd3, 0x30,
	0x10, 0xde, 0x26, 0xbb, 0xa5, 0x3b, 0xa1, 0x62, 0xb1, 0x78, 0x2c, 0x11, 0xa2, 0x34, 0x27, 0x2e,
	0xe4, 0x50, 0x40, 0xe2, 0xc2, 0xa1, 0x50, 0x41, 0x91, 0x8a, 0x84, 0x82, 0x54, 0x8e, 0x55, 0x70,
	0xa6, 0xc1, 0x22, 0xb2, 0xdb, 0xc4, 0x6d, 0xd5, 0x1b, 0x3f, 0x1d, 0xd9, 0x4e, 0xd2, 0xe6, 0x85,
	0xb8, 0x70, 0x9b, 0xf9, 0xec, 0xef, 0xe1, 0x49, 0x6c, 0x78, 0x20, 0x43, 0xc6, 0xe5, 0x4b, 0x99,
	0x86, 0xf4, 0x17, 0xe3, 0xb1, 0xbf, 0x49, 0x85, 0x14, 0x64, 0xa8, 0xd1, 0x02, 0xf4, 0xbe, 0xc3,
	0xf0, 0x23, 0x4b, 0x24, 0xa6, 0x01, 0x6e, 0x77, 0x98, 0x49, 0xf2, 0x08, 0xfa, 0x31, 0xca, 0x25,
	0x26, 0xb7, 0xbd, 0xe7, 0xbd, 0x17, 0x83, 0x20, 0xef, 0x14, 0xce, 0x38, 0x55, 0xb8, 0x65, 0x70,
	0xd3, 0x29, 0x3c, 0x42, 0x8d, 0xdb, 0x06, 0x37, 0x9d, 0x27, 0xc0, 0x29, 0x84, 0x37, 0xc9, 0x91,
	0xdc, 0xc2, 0x9d, 0x6c, 0x47, 0x29, 0x66, 0x59, 0xae, 0x5b, 0xb4, 0x67, 0x86, 0x56, 0x87, 0xa1,
	0xdd, 0x61, 0x78, 0x59, 0x31, 0x7c, 0x0d, 0xb0, 0x10, 0x71, 0x71, 0x0c, 0x02, 0x97, 0x8c, 0xaf,
	0x85, 0x36, 0xbb, 0x0e, 0x74, 0xad, 0x30, 0x2a, 0x22, 0xcc, 0x7d, 0x74, 0xed, 0x4d, 0x60, 0xa0,
	0x59, 0x2a, 0xe3, 0xbf, 0x72, 0xde, 0xc0, 0xbd, 0x25, 0x26, 0x82, 0x32, 0x79, 0x2c, 0xec, 0x6e,
	0xc0, 0x4e, 0x71, 0x9b, 0x33, 0x55, 0xa9, 0x90, 0x44, 0xc4, 0x39, 0x4f, 0x95, 0xde, 0x3b, 0x18,
	0x9e, 0x68, 0xca, 0xcf, 0x85, 0xc1, 0x3e, 0x07, 0x34, 0xf3, 0x2a, 0x28, 0xfb, 0x16, 0xfa, 0x5b,
	0x20, 0x9f, 0xf5, 0x04, 0xea, 0xc6, 0x8c, 0xd3, 0x9c, 0xae, 0xca, 0x16, 0xe6, 0x4f, 0xb8, 0xa9,
	0x30, 0x95, 0xf7, 0x08, 0x9c, 0x14, 0xe5, 0x2e, 0xe5, 0x2b, 0x7d, 0x3c, 0xf3, 0x4d, 0xc0, 0x40,
	0x1f, 0x44, 0x84, 0x64, 0x0c, 0x77, 0x39, 0x1e, 0x56, 0x65, 0x40, 0x4b, 0x3b, 0x38, 0x1c, 0x0f,
	0xcb, 0x5a, 0x46, 0xbb, 0x92, 0x71, 0x86, 0x6d, 0x19, 0x23, 0x2c, 0x33, 0x46, 0xd8, 0x91, 0xb1,
	0xc2, 0xfc, 0x6f, 0x19, 0x27, 0xbf, 0x2d, 0xb8, 0x9a, 0xa5, 0x6c, 0x8f, 0xe4, 0x0b, 0x38, 0x9f,
	0xf4, 0xbf, 0x66, 0xb6, 0x3e, 0xf3, 0x2b, 0x57, 0xc3, 0xaf, 0x1d, 0xc3, 0x7d, 0xda, 0xb9, 0xbe,
	0x49, 0x8e, 0xde, 0x05, 0xf9, 0x06, 0xce, 0xd9, 0x98, 0xc9, 0xb8, 0xb6, 0xbd, 0xf9, 0xf1, 0xdc,
	0xd1, 0xdf, 0xb6, 0x94, 0xa2, 0x67, 0x73, 0x69, 0x88, 0x36, 0xa7, 0xdd, 0x10, 0xad, 0x8f, 0xd5,
	0xbb, 0x98, 0xcc, 0xc1, 0x5e, 0x88, 0x98, 0x4c, 0xe1, 0x3a, 0x11, 0xf1, 0x94, 0x4a, 0x26, 0x38,
	0x79, 0x52, 0xa3, 0x9d, 0xee, 0x92, 0xfb, 0xb8, 0x6d, 0xc9, 0x28, 0x05, 0xd0, 0x37, 0xb7, 0x9c,
	0xcc, 0x01, 0xd6, 0xba, 0x9a, 0x85, 0x32, 0x24, 0xf5, 0x59, 0x55, 0xde, 0x18, 0xd7, 0xed, 0x58,
	0xd5, 0x9a, 0xef, 0x1f, 0xc2, 0x7d, 0x26, 0xfc, 0xea, 0xe3, 0xf5, 0xb5, 0xf7, 0xa3, 0xaf, 0xdf,
	0xaf, 0x57, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa7, 0x6d, 0x75, 0xd7, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriveClient is the client API for Drive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriveClient interface {
	//rpc call for returning the current velocity
	GetVelocity(ctx context.Context, in *VelocityRequest, opts ...grpc.CallOption) (*VelocityReply, error)
	//rpc call for increasing the velocity
	IncVelocity(ctx context.Context, in *IncVelocityRequest, opts ...grpc.CallOption) (*IncVelocityReply, error)
	//rpc call for decreasing the velocity
	DecVelocity(ctx context.Context, in *DecVelocityRequest, opts ...grpc.CallOption) (*DecVelocityReply, error)
}

type driveClient struct {
	cc *grpc.ClientConn
}

func NewDriveClient(cc *grpc.ClientConn) DriveClient {
	return &driveClient{cc}
}

func (c *driveClient) GetVelocity(ctx context.Context, in *VelocityRequest, opts ...grpc.CallOption) (*VelocityReply, error) {
	out := new(VelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/GetVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) IncVelocity(ctx context.Context, in *IncVelocityRequest, opts ...grpc.CallOption) (*IncVelocityReply, error) {
	out := new(IncVelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/IncVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) DecVelocity(ctx context.Context, in *DecVelocityRequest, opts ...grpc.CallOption) (*DecVelocityReply, error) {
	out := new(DecVelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/DecVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriveServer is the server API for Drive service.
type DriveServer interface {
	//rpc call for returning the current velocity
	GetVelocity(context.Context, *VelocityRequest) (*VelocityReply, error)
	//rpc call for increasing the velocity
	IncVelocity(context.Context, *IncVelocityRequest) (*IncVelocityReply, error)
	//rpc call for decreasing the velocity
	DecVelocity(context.Context, *DecVelocityRequest) (*DecVelocityReply, error)
}

// UnimplementedDriveServer can be embedded to have forward compatible implementations.
type UnimplementedDriveServer struct {
}

func (*UnimplementedDriveServer) GetVelocity(ctx context.Context, req *VelocityRequest) (*VelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVelocity not implemented")
}
func (*UnimplementedDriveServer) IncVelocity(ctx context.Context, req *IncVelocityRequest) (*IncVelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncVelocity not implemented")
}
func (*UnimplementedDriveServer) DecVelocity(ctx context.Context, req *DecVelocityRequest) (*DecVelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecVelocity not implemented")
}

func RegisterDriveServer(s *grpc.Server, srv DriveServer) {
	s.RegisterService(&_Drive_serviceDesc, srv)
}

func _Drive_GetVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).GetVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/GetVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).GetVelocity(ctx, req.(*VelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_IncVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).IncVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/IncVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).IncVelocity(ctx, req.(*IncVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_DecVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).DecVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/DecVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).DecVelocity(ctx, req.(*DecVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tainttracking.Drive",
	HandlerType: (*DriveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVelocity",
			Handler:    _Drive_GetVelocity_Handler,
		},
		{
			MethodName: "IncVelocity",
			Handler:    _Drive_IncVelocity_Handler,
		},
		{
			MethodName: "DecVelocity",
			Handler:    _Drive_DecVelocity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taint-tracking.proto",
}

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogClient interface {
	//rpc call for logginng info
	LogAction(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) LogAction(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogReply, error) {
	out := new(LogReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Log/logAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
type LogServer interface {
	//rpc call for logginng info
	LogAction(context.Context, *LogRequest) (*LogReply, error)
}

// UnimplementedLogServer can be embedded to have forward compatible implementations.
type UnimplementedLogServer struct {
}

func (*UnimplementedLogServer) LogAction(ctx context.Context, req *LogRequest) (*LogReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogAction not implemented")
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_LogAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).LogAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Log/LogAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).LogAction(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tainttracking.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "logAction",
			Handler:    _Log_LogAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taint-tracking.proto",
}

// FilterClient is the client API for Filter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilterClient interface {
	FilterData(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error)
}

type filterClient struct {
	cc *grpc.ClientConn
}

func NewFilterClient(cc *grpc.ClientConn) FilterClient {
	return &filterClient{cc}
}

func (c *filterClient) FilterData(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterReply, error) {
	out := new(FilterReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Filter/filterData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterServer is the server API for Filter service.
type FilterServer interface {
	FilterData(context.Context, *FilterRequest) (*FilterReply, error)
}

// UnimplementedFilterServer can be embedded to have forward compatible implementations.
type UnimplementedFilterServer struct {
}

func (*UnimplementedFilterServer) FilterData(ctx context.Context, req *FilterRequest) (*FilterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterData not implemented")
}

func RegisterFilterServer(s *grpc.Server, srv FilterServer) {
	s.RegisterService(&_Filter_serviceDesc, srv)
}

func _Filter_FilterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterServer).FilterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Filter/FilterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterServer).FilterData(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Filter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tainttracking.Filter",
	HandlerType: (*FilterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "filterData",
			Handler:    _Filter_FilterData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taint-tracking.proto",
}
