// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taint-tracking/taint-tracking.proto

package tainttracking

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VelocityRequest struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VelocityRequest) Reset()         { *m = VelocityRequest{} }
func (m *VelocityRequest) String() string { return proto.CompactTextString(m) }
func (*VelocityRequest) ProtoMessage()    {}
func (*VelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{0}
}

func (m *VelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VelocityRequest.Unmarshal(m, b)
}
func (m *VelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VelocityRequest.Marshal(b, m, deterministic)
}
func (m *VelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VelocityRequest.Merge(m, src)
}
func (m *VelocityRequest) XXX_Size() int {
	return xxx_messageInfo_VelocityRequest.Size(m)
}
func (m *VelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VelocityRequest proto.InternalMessageInfo

func (m *VelocityRequest) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type VelocityReply struct {
	Velocity             int32    `protobuf:"varint,1,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VelocityReply) Reset()         { *m = VelocityReply{} }
func (m *VelocityReply) String() string { return proto.CompactTextString(m) }
func (*VelocityReply) ProtoMessage()    {}
func (*VelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{1}
}

func (m *VelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VelocityReply.Unmarshal(m, b)
}
func (m *VelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VelocityReply.Marshal(b, m, deterministic)
}
func (m *VelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VelocityReply.Merge(m, src)
}
func (m *VelocityReply) XXX_Size() int {
	return xxx_messageInfo_VelocityReply.Size(m)
}
func (m *VelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_VelocityReply proto.InternalMessageInfo

func (m *VelocityReply) GetVelocity() int32 {
	if m != nil {
		return m.Velocity
	}
	return 0
}

type IncVelocityRequest struct {
	Inc                  int32    `protobuf:"varint,1,opt,name=inc,proto3" json:"inc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncVelocityRequest) Reset()         { *m = IncVelocityRequest{} }
func (m *IncVelocityRequest) String() string { return proto.CompactTextString(m) }
func (*IncVelocityRequest) ProtoMessage()    {}
func (*IncVelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{2}
}

func (m *IncVelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncVelocityRequest.Unmarshal(m, b)
}
func (m *IncVelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncVelocityRequest.Marshal(b, m, deterministic)
}
func (m *IncVelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncVelocityRequest.Merge(m, src)
}
func (m *IncVelocityRequest) XXX_Size() int {
	return xxx_messageInfo_IncVelocityRequest.Size(m)
}
func (m *IncVelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncVelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncVelocityRequest proto.InternalMessageInfo

func (m *IncVelocityRequest) GetInc() int32 {
	if m != nil {
		return m.Inc
	}
	return 0
}

type IncVelocityReply struct {
	ReturnCode           bool     `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	NewVelocity          int32    `protobuf:"varint,2,opt,name=new_velocity,json=newVelocity,proto3" json:"new_velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncVelocityReply) Reset()         { *m = IncVelocityReply{} }
func (m *IncVelocityReply) String() string { return proto.CompactTextString(m) }
func (*IncVelocityReply) ProtoMessage()    {}
func (*IncVelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{3}
}

func (m *IncVelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncVelocityReply.Unmarshal(m, b)
}
func (m *IncVelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncVelocityReply.Marshal(b, m, deterministic)
}
func (m *IncVelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncVelocityReply.Merge(m, src)
}
func (m *IncVelocityReply) XXX_Size() int {
	return xxx_messageInfo_IncVelocityReply.Size(m)
}
func (m *IncVelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IncVelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_IncVelocityReply proto.InternalMessageInfo

func (m *IncVelocityReply) GetReturnCode() bool {
	if m != nil {
		return m.ReturnCode
	}
	return false
}

func (m *IncVelocityReply) GetNewVelocity() int32 {
	if m != nil {
		return m.NewVelocity
	}
	return 0
}

type DecVelocityRequest struct {
	Dec                  int32    `protobuf:"varint,1,opt,name=dec,proto3" json:"dec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecVelocityRequest) Reset()         { *m = DecVelocityRequest{} }
func (m *DecVelocityRequest) String() string { return proto.CompactTextString(m) }
func (*DecVelocityRequest) ProtoMessage()    {}
func (*DecVelocityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{4}
}

func (m *DecVelocityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecVelocityRequest.Unmarshal(m, b)
}
func (m *DecVelocityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecVelocityRequest.Marshal(b, m, deterministic)
}
func (m *DecVelocityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecVelocityRequest.Merge(m, src)
}
func (m *DecVelocityRequest) XXX_Size() int {
	return xxx_messageInfo_DecVelocityRequest.Size(m)
}
func (m *DecVelocityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecVelocityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecVelocityRequest proto.InternalMessageInfo

func (m *DecVelocityRequest) GetDec() int32 {
	if m != nil {
		return m.Dec
	}
	return 0
}

type DecVelocityReply struct {
	ReturnCode           bool     `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	NewVelocity          int32    `protobuf:"varint,2,opt,name=new_velocity,json=newVelocity,proto3" json:"new_velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecVelocityReply) Reset()         { *m = DecVelocityReply{} }
func (m *DecVelocityReply) String() string { return proto.CompactTextString(m) }
func (*DecVelocityReply) ProtoMessage()    {}
func (*DecVelocityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c38093ad258e0ed0, []int{5}
}

func (m *DecVelocityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecVelocityReply.Unmarshal(m, b)
}
func (m *DecVelocityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecVelocityReply.Marshal(b, m, deterministic)
}
func (m *DecVelocityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecVelocityReply.Merge(m, src)
}
func (m *DecVelocityReply) XXX_Size() int {
	return xxx_messageInfo_DecVelocityReply.Size(m)
}
func (m *DecVelocityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DecVelocityReply.DiscardUnknown(m)
}

var xxx_messageInfo_DecVelocityReply proto.InternalMessageInfo

func (m *DecVelocityReply) GetReturnCode() bool {
	if m != nil {
		return m.ReturnCode
	}
	return false
}

func (m *DecVelocityReply) GetNewVelocity() int32 {
	if m != nil {
		return m.NewVelocity
	}
	return 0
}

func init() {
	proto.RegisterType((*VelocityRequest)(nil), "tainttracking.VelocityRequest")
	proto.RegisterType((*VelocityReply)(nil), "tainttracking.VelocityReply")
	proto.RegisterType((*IncVelocityRequest)(nil), "tainttracking.IncVelocityRequest")
	proto.RegisterType((*IncVelocityReply)(nil), "tainttracking.IncVelocityReply")
	proto.RegisterType((*DecVelocityRequest)(nil), "tainttracking.DecVelocityRequest")
	proto.RegisterType((*DecVelocityReply)(nil), "tainttracking.DecVelocityReply")
}

func init() {
	proto.RegisterFile("taint-tracking/taint-tracking.proto", fileDescriptor_c38093ad258e0ed0)
}

var fileDescriptor_c38093ad258e0ed0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x4a, 0xa5, 0x4e, 0x2c, 0xd6, 0x01, 0x41, 0x82, 0x58, 0xbb, 0x05, 0x11, 0xc4,
	0x08, 0xfa, 0x0f, 0xb4, 0x17, 0x0f, 0x82, 0x44, 0xc8, 0xb5, 0xd4, 0xcd, 0x50, 0x16, 0xc3, 0x6e,
	0xba, 0x6e, 0x5b, 0x72, 0xf3, 0xa7, 0x4b, 0xd6, 0x36, 0x66, 0x93, 0xe8, 0xc9, 0xdb, 0xce, 0x9b,
	0x8f, 0xf7, 0x96, 0xc7, 0xc0, 0xc4, 0xcc, 0x85, 0x34, 0x37, 0x46, 0xcf, 0xf9, 0xbb, 0x90, 0x8b,
	0x5b, 0x77, 0x0c, 0x33, 0xad, 0x8c, 0xc2, 0x81, 0x55, 0x77, 0x22, 0x9b, 0xc0, 0x51, 0x4c, 0xa9,
	0xe2, 0xc2, 0xe4, 0x11, 0x2d, 0x57, 0xf4, 0x61, 0x70, 0x08, 0x7b, 0x9a, 0x96, 0xa7, 0xde, 0x85,
	0x77, 0x75, 0x10, 0x15, 0x4f, 0x76, 0x0d, 0x83, 0x1f, 0x28, 0x4b, 0x73, 0x0c, 0xa0, 0xbf, 0xde,
	0x0a, 0x96, 0xeb, 0x45, 0xe5, 0xcc, 0x2e, 0x01, 0x9f, 0x24, 0x6f, 0x31, 0x15, 0x92, 0x6f, 0xe1,
	0xe2, 0xc9, 0x62, 0x18, 0x3a, 0x5c, 0xe1, 0x3b, 0x02, 0x5f, 0x93, 0x59, 0x69, 0x39, 0xe3, 0x2a,
	0x21, 0x4b, 0xf7, 0x23, 0xf8, 0x96, 0x1e, 0x55, 0x42, 0x38, 0x86, 0x43, 0x49, 0x9b, 0x59, 0x19,
	0xde, 0xb5, 0x7e, 0xbe, 0xa4, 0x4d, 0x5c, 0xc9, 0x9f, 0x52, 0x5b, 0x7e, 0x42, 0x65, 0x7e, 0x42,
	0x36, 0xdf, 0xe1, 0xfe, 0x29, 0xff, 0xee, 0xb3, 0x0b, 0xbd, 0xa9, 0x16, 0x6b, 0xc2, 0x67, 0xf0,
	0x17, 0x64, 0x76, 0x0b, 0x3c, 0x0f, 0x9d, 0xea, 0xc3, 0xda, 0x17, 0x83, 0xb3, 0x5f, 0xf7, 0x59,
	0x9a, 0xb3, 0x0e, 0xbe, 0x82, 0x5f, 0x29, 0x0c, 0xc7, 0x35, 0xbc, 0x59, 0x7a, 0x30, 0xfa, 0x0b,
	0x29, 0x4d, 0x2b, 0x2d, 0x34, 0x4c, 0x9b, 0x4d, 0x36, 0x4c, 0xeb, 0x25, 0xb2, 0xce, 0xc3, 0x09,
	0x1c, 0x0b, 0x15, 0xba, 0xe7, 0xf7, 0xe2, 0xbd, 0xed, 0xdb, 0x0b, 0xbc, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x38, 0x0b, 0x95, 0xa8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriveClient is the client API for Drive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriveClient interface {
	//rpc call for returning the current velocity
	GetVelocity(ctx context.Context, in *VelocityRequest, opts ...grpc.CallOption) (*VelocityReply, error)
	//rpc call for increasing the velocity
	IncVelocity(ctx context.Context, in *IncVelocityRequest, opts ...grpc.CallOption) (*IncVelocityReply, error)
	//rpc call for decreasing the velocity
	DecVelocity(ctx context.Context, in *DecVelocityRequest, opts ...grpc.CallOption) (*DecVelocityReply, error)
}

type driveClient struct {
	cc *grpc.ClientConn
}

func NewDriveClient(cc *grpc.ClientConn) DriveClient {
	return &driveClient{cc}
}

func (c *driveClient) GetVelocity(ctx context.Context, in *VelocityRequest, opts ...grpc.CallOption) (*VelocityReply, error) {
	out := new(VelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/getVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) IncVelocity(ctx context.Context, in *IncVelocityRequest, opts ...grpc.CallOption) (*IncVelocityReply, error) {
	out := new(IncVelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/IncVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driveClient) DecVelocity(ctx context.Context, in *DecVelocityRequest, opts ...grpc.CallOption) (*DecVelocityReply, error) {
	out := new(DecVelocityReply)
	err := c.cc.Invoke(ctx, "/tainttracking.Drive/DecVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriveServer is the server API for Drive service.
type DriveServer interface {
	//rpc call for returning the current velocity
	GetVelocity(context.Context, *VelocityRequest) (*VelocityReply, error)
	//rpc call for increasing the velocity
	IncVelocity(context.Context, *IncVelocityRequest) (*IncVelocityReply, error)
	//rpc call for decreasing the velocity
	DecVelocity(context.Context, *DecVelocityRequest) (*DecVelocityReply, error)
}

// UnimplementedDriveServer can be embedded to have forward compatible implementations.
type UnimplementedDriveServer struct {
}

func (*UnimplementedDriveServer) GetVelocity(ctx context.Context, req *VelocityRequest) (*VelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVelocity not implemented")
}
func (*UnimplementedDriveServer) IncVelocity(ctx context.Context, req *IncVelocityRequest) (*IncVelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncVelocity not implemented")
}
func (*UnimplementedDriveServer) DecVelocity(ctx context.Context, req *DecVelocityRequest) (*DecVelocityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecVelocity not implemented")
}

func RegisterDriveServer(s *grpc.Server, srv DriveServer) {
	s.RegisterService(&_Drive_serviceDesc, srv)
}

func _Drive_GetVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).GetVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/GetVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).GetVelocity(ctx, req.(*VelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_IncVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).IncVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/IncVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).IncVelocity(ctx, req.(*IncVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drive_DecVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriveServer).DecVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tainttracking.Drive/DecVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriveServer).DecVelocity(ctx, req.(*DecVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tainttracking.Drive",
	HandlerType: (*DriveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getVelocity",
			Handler:    _Drive_GetVelocity_Handler,
		},
		{
			MethodName: "IncVelocity",
			Handler:    _Drive_IncVelocity_Handler,
		},
		{
			MethodName: "DecVelocity",
			Handler:    _Drive_DecVelocity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taint-tracking/taint-tracking.proto",
}
